export const AUTH_LOGIN = 'AUTH_LOGIN'
export const AUTH_LOGOUT = 'AUTH_LOGOUT'
export const FETCH_TASKS = 'FETCH_TASKS'
export const FETCH_TASK = 'FETCH_TASK'
export const UPDATE_TASK = 'UPDATE_TASK'
